@MyCinemaDiary_HostAddress = http://localhost:5253

GET {{MyCinemaDiary_HostAddress}}/moviesearch/?query=The+Godfather&limit=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiNjJhMjMyMjQtNzNkMC00ODViLTgxNjYtMzI3NTcxYjdlZjc2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiZXhwIjoxNzM5NDUzMzc0fQ.PdEH_RH6ppPHc4Nr2fu91BNS5fW8knSxe8TKg9DQzZ8
Accept: application/json

###
GET {{MyCinemaDiary_HostAddress}}/movies/
Accept: application/json



###
POST {{MyCinemaDiary_HostAddress}}/movies/
Content-Type: application/json

{
    "id": 0,
    "country": "usa",
    "director": "Francis Ford Coppola",
    "extendedTitle": "The Godfather: Part II (1974)",
    "name": "The Godfather: Part II",
    "firstAirTime": "1974-12-18",
    "overview": "Michael Corleone ruthlessly expands the family's criminal empire amid flashbacks of his father Vito's rise from Sicilian orphan to New York godfather.",
    "primaryLanguage": "eng",
    "primaryType": "movie",
    "status": "Released",
    "year": 1974,
    "slug": "the-godfather-part-ii",
    "imageUrl": "https://artworks.thetvdb.com/banners/v4/movie/780/posters/6318849d18674.jpg",
    "thumbnail": "https://artworks.thetvdb.com/banners/v4/movie/780/posters/6318849d18674_t.jpg",
    "tvdbId": "780",
    "imdbId": "tt0071562",
    "tmdbId": "240",
    "movieGenres": [
        "Crime",
        "Drama"
    ]
}

### Register User Test
POST {{MyCinemaDiary_HostAddress}}/user/register
Content-Type: application/json

{
    "Name": "John Doe",
    "Username": "johndoe",
    "Password": "SecurePassword123"
}

### Login User Test
POST {{MyCinemaDiary_HostAddress}}/user/login
Content-Type: application/json

{
    "Username": "johndoe",
    "Password": "SecurePassword123"
}


###  
GET {{MyCinemaDiary_HostAddress}}/diaryentries/?movieId=1&userId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiNjJhMjMyMjQtNzNkMC00ODViLTgxNjYtMzI3NTcxYjdlZjc2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiZXhwIjoxNzM5NDUzMzc0fQ.PdEH_RH6ppPHc4Nr2fu91BNS5fW8knSxe8TKg9DQzZ8
Accept: application/json

###  
GET {{MyCinemaDiary_HostAddress}}/diaryentries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiODVhZjUwMTMtN2M1Mi00MDU1LTliMTEtNzM4NGZiZGE1OTg5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiZXhwIjoxNzM5NDc2NTM3fQ.ftV49ZzVtIW_8tf3e_6uzsAQgAY1OsR7WdBlD_QZV-c
Accept: application/json


###
Post {{MyCinemaDiary_HostAddress}}/diaryentries/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiODVhZjUwMTMtN2M1Mi00MDU1LTliMTEtNzM4NGZiZGE1OTg5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiZXhwIjoxNzM5NDc2NTM3fQ.ftV49ZzVtIW_8tf3e_6uzsAQgAY1OsR7WdBlD_QZV-c
Content-Type: application/json
{
    "Rating": 5,
    "Review": "This is a great movie. I loved it!",
    "Title": "Must watch film!",
    "Date": "2021-01-01",
    "UserId": 7,
    "MovieId": 1
}

###
Post {{MyCinemaDiary_HostAddress}}/diaryentries/save
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwianRpIjoiODVhZjUwMTMtN2M1Mi00MDU1LTliMTEtNzM4NGZiZGE1OTg5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI3IiwiZXhwIjoxNzM5NDc2NTM3fQ.ftV49ZzVtIW_8tf3e_6uzsAQgAY1OsR7WdBlD_QZV-c
Content-Type: application/json
{
    "Rating": 5,
    "Review": "Wow is this a great movie. I loved it!",
    "Title": "Must watch film!",
    "Date": "2024-01-01",
    "UserId": 7,
    "MovieId": 1
}